import type { Metadata } from "next";

const metadata: Metadata = {
  title: "TJ Eastmond",
  description:
    "TJ Eastmond - Girl Dad, Husband, Gamer, Cult Leader, Data Engineer, and Software Engineer",
  applicationName: "tjeastmond.com",
  keywords: [
    "AI",
    "Artificial Intelligence",
    "Cult Leader",
    "CultLeader.io",
    "Data Engineer",
    "Data Science",
    "Data",
    "dbt",
    "Engineering Leadership",
    "Engineering Management",
    "Engineering Manager",
    "Engineering",
    "Go",
    "Golang",
    "JavaScript",
    "LLM",
    "Machine Learning",
    "ML",
    "MongoDB",
    "MySQL",
    "Node.js",
    "Postgres",
    "Python",
    "Software Development",
    "Software Engineer",
    "Software Engineering",
    "Spiteshow",
    "T.J. Eastmond",
    "T.J.",
    "TJ Eastmond",
    "TJ",
    "Girl Dad",
    "Gamer",
    "Marvel SNAP",
    "SNAP",
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { type: "image/png", sizes: "16x16", url: "/images/icons/favicon-16x16.png" },
      { type: "image/png", sizes: "32x32", url: "/images/icons/favicon-32x32.png" },
    ],
    shortcut: ["/images/icons/favicon.ico"],
    apple: [{ url: "/images/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    other: [
      { rel: "mask-icon", url: "/images/icons/safari-pinned-tab.svg", color: "#da532c" },
      { rel: "manifest", url: "/images/icons/site.webmanifest" },
    ],
  },
  appleWebApp: {
    statusBarStyle: "black-translucent",
    title: "tjeastmond.com",
  },
};

export default metadata;
